development:
  adapter: postgresql
  encoding: unicode
  database: humblecasa_dev
  pool: 5
  username: jasonwardwell
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: humblecasa_test
  pool: 5
  username: jasonwardwell
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: humblecasa_prod
  pool: 5
  username: jasonwardwell
  password: